; Copyright (c) 2026 Tom Chapman. All rights reserved.
; Editor defaults for CombatForge. Keep Play-In-Editor STANDALONE so pressing Play never
; auto-hosts a LAN listen server — hosting is an explicit HOST LAN GAME menu action only.

[/Script/UnrealEd.LevelEditorPlaySettings]
PlayNetMode=PIE_Standalone
RunUnderOneProcess=True
PlayNumberOfClients=1
bLaunchSeparateServer=False
